/// <reference types="cypress" />
import Index from '../page_object/index'
const jsonUtils = require('../resources/credentials');

describe('base',()=>{
    const index = new Index()
    beforeEach(() => {
        cy.visit('/')
    })
    it('Deve fazer login',()=>{
    cy.get('.login').click()
    index.signin('abanzy@gmail.com','123456')
    cy.url().should('include', 'http://automationpractice.com/index.php?controller=my-account',{timeout:15000})
    })
    it('Deve fazer login e logout',()=>{
    cy.get('.login').click()
    index.signin('abanzy@gmail.com','123456')
    cy.url().should('include', 'http://automationpractice.com/index.php?controller=my-account',{timeout:15000})
    index.signout()
    })
    it('Deve adicionar roupa ao carrinho',()=>{
    index.searchFor('Faded Short Sleeve T-shirts')
    index.mouseOver('.product-container')
    index.addToCart()
    index.checkAddtoCart()
    index.proceedToCheckout()
})
it('Deve adicionar e remover a roupa do carrinho',()=>{
    index.searchFor('Faded Short Sleeve T-shirts')
    index.mouseOver('.product-container')
    index.addToCart()
    index.checkAddtoCart()
    index.proceedToCheckout()
    index.checkCartContentFor('Faded Short Sleeve T-shirts')
    index.removeCartItem(0)
    cy.get('.alert').should('be.visible')
})
it('Deve adicionar roupa do carrinho, login e checkout order pagando por bank wire',()=>{
    index.searchFor('Faded Short Sleeve T-shirts')
    index.mouseOver('.product-container')
    index.addToCart()
    index.checkAddtoCart()
    index.proceedToCheckout()
    index.checkCartContentFor('Faded Short Sleeve T-shirts')
    index.clickProceedToCartCheckoutButton()
    index.signin('abanzy@gmail.com','123456')
    cy.url().should('include', 'http://automationpractice.com/index.php?controller=order&step=1&multi-shipping=0',{timeout:15000})
    index.clickProceedToCartCheckoutButton()
    index.checkTheTermsOfAgreement()
    index.clickProceedToCartCheckoutButton()
    index.selectPayByBankWire()
    index.confirmOrder()
    cy.contains('Your order on My Store is complete.').should('be.visible')
})
it('Deve adicionar roupa do carrinho, login e checkout pagando por check',()=>{
    index.searchFor('Faded Short Sleeve T-shirts')
    index.mouseOver('.product-container')
    index.addToCart()
    index.checkAddtoCart()
    index.proceedToCheckout()
    index.checkCartContentFor('Faded Short Sleeve T-shirts')
    index.clickProceedToCartCheckoutButton()
    index.signin('abanzy@gmail.com','123456')
    cy.url().should('include', 'http://automationpractice.com/index.php?controller=order&step=1&multi-shipping=0',{timeout:15000})
    index.clickProceedToCartCheckoutButton()
    index.checkTheTermsOfAgreement()
    index.clickProceedToCartCheckoutButton()
    index.selectPayByCheck()
    index.confirmOrder()
    cy.contains('Your order on My Store is complete.').should('be.visible')
})
})